/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcjava;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabrício
 */
public class CalculadoraJava extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraJava
     */
    public CalculadoraJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        opc7 = new javax.swing.JButton();
        opc4 = new javax.swing.JButton();
        opc1 = new javax.swing.JButton();
        opc8 = new javax.swing.JButton();
        opc5 = new javax.swing.JButton();
        opc2 = new javax.swing.JButton();
        opc9 = new javax.swing.JButton();
        opc6 = new javax.swing.JButton();
        opc3 = new javax.swing.JButton();
        valor2 = new javax.swing.JTextField();
        adicao = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        valor1 = new javax.swing.JTextField();
        opc0 = new javax.swing.JButton();
        limpa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        operador.setEditable(false);
        operador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("=");

        resultado.setEditable(false);
        resultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        opc7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc7.setText("7");
        opc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc7ActionPerformed(evt);
            }
        });

        opc4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc4.setText("4");
        opc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc4ActionPerformed(evt);
            }
        });

        opc1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc1.setText("1");
        opc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc1ActionPerformed(evt);
            }
        });

        opc8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc8.setText("8");
        opc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc8ActionPerformed(evt);
            }
        });

        opc5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc5.setText("5");
        opc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc5ActionPerformed(evt);
            }
        });

        opc2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc2.setText("2");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });

        opc9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc9.setText("9");
        opc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc9ActionPerformed(evt);
            }
        });

        opc6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc6.setText("6");
        opc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc6ActionPerformed(evt);
            }
        });

        opc3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc3.setText("3");
        opc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc3ActionPerformed(evt);
            }
        });

        valor2.setEditable(false);
        valor2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        adicao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adicao.setText("+");
        adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicaoActionPerformed(evt);
            }
        });

        divisao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        divisao.setText("/");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });

        subtracao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });

        calcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multiplicacao.setText("x");
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });

        valor1.setEditable(false);
        valor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        opc0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        opc0.setText("0");
        opc0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc0ActionPerformed(evt);
            }
        });

        limpa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        limpa.setText("Limpar");
        limpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("Calculadora Simples!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opc1)
                            .addComponent(opc4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(opc7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opc2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opc3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opc8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opc9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(opc6))
                            .addComponent(opc0))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multiplicacao)
                                .addGap(18, 18, 18)
                                .addComponent(divisao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adicao)
                                .addGap(18, 18, 18)
                                .addComponent(subtracao))
                            .addComponent(calcular)
                            .addComponent(limpa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc7)
                            .addComponent(opc8)
                            .addComponent(opc9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc4)
                            .addComponent(opc5)
                            .addComponent(opc6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opc1)
                            .addComponent(opc2)
                            .addComponent(opc3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opc0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adicao)
                            .addComponent(subtracao))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divisao)
                            .addComponent(multiplicacao))
                        .addGap(18, 18, 18)
                        .addComponent(calcular)
                        .addGap(18, 18, 18)
                        .addComponent(limpa)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc1ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(1));
        } else {
            valor2.setText(Integer.toString(1));
        }
    }//GEN-LAST:event_opc1ActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed

        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(2));
        } else {
            valor2.setText(Integer.toString(2));
        }
    }//GEN-LAST:event_opc2ActionPerformed

    private void opc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc3ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(3));
        } else {
            valor2.setText(Integer.toString(3));
        }
    }//GEN-LAST:event_opc3ActionPerformed

    private void opc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc4ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(4));
        } else {
            valor2.setText(Integer.toString(4));
        }
    }//GEN-LAST:event_opc4ActionPerformed

    private void opc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc5ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(5));
        } else {
            valor2.setText(Integer.toString(5));
        }
    }//GEN-LAST:event_opc5ActionPerformed

    private void opc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc6ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(6));
        } else {
            valor2.setText(Integer.toString(6));
        }
    }//GEN-LAST:event_opc6ActionPerformed

    private void opc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc7ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(7));
        } else {
            valor2.setText(Integer.toString(7));
        }
    }//GEN-LAST:event_opc7ActionPerformed

    private void opc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc8ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(8));
        } else {
            valor2.setText(Integer.toString(8));
        };
    }//GEN-LAST:event_opc8ActionPerformed

    private void opc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc9ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(9));
        } else {
            valor2.setText(Integer.toString(9));
        }
    }//GEN-LAST:event_opc9ActionPerformed

    private void adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicaoActionPerformed
        operador.setText("+");
    }//GEN-LAST:event_adicaoActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
        operador.setText("-");
    }//GEN-LAST:event_subtracaoActionPerformed

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacaoActionPerformed
        operador.setText("x");
    }//GEN-LAST:event_multiplicacaoActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        operador.setText("/");
    }//GEN-LAST:event_divisaoActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        try {
            int v1 = Integer.parseInt(valor1.getText());
            int v2 = Integer.parseInt(valor2.getText());
     
            switch (operador.getText()) {
                case "+":
                    resultado.setText(Integer.toString(Calculo.Adicao(v1, v2)));
                    break;
                case "-":
                    resultado.setText(Integer.toString(Calculo.Subtracao(v1, v2)));
                    break;
                case "x":
                    resultado.setText(Integer.toString(Calculo.Multiplicacao(v1, v2)));
                    break;
                default:
                    resultado.setText(Float.toString(Calculo.Divisao(v1, v2)));
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void opc0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc0ActionPerformed
        if (valor1.getText().equals("")) {
            valor1.setText(Integer.toString(0));
        } else {
            valor2.setText(Integer.toString(0));
        }
    }//GEN-LAST:event_opc0ActionPerformed

    private void limpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaActionPerformed
        valor1.setText("");
        valor2.setText("");
        operador.setText("");
        resultado.setText("");
    }//GEN-LAST:event_limpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicao;
    private javax.swing.JButton calcular;
    private javax.swing.JButton divisao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton limpa;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton opc0;
    private javax.swing.JButton opc1;
    private javax.swing.JButton opc2;
    private javax.swing.JButton opc3;
    private javax.swing.JButton opc4;
    private javax.swing.JButton opc5;
    private javax.swing.JButton opc6;
    private javax.swing.JButton opc7;
    private javax.swing.JButton opc8;
    private javax.swing.JButton opc9;
    private javax.swing.JTextField operador;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton subtracao;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
